seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listing.rb
    disabled: false
    page_type: listing

  - file: ./parsers/videos.rb
    disabled: false
    page_type: videos

exporters:
  - file: ./exporters/product_json.yaml
  